apiVersion: v1
kind: Service
metadata: 
  name: packages-service
spec:
  # porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: packages
  ports:
    - name: packages
      protocol: TCP
      port: 3000
      targetPort: 3000