apiVersion: apps/v1
kind: Deployment
metadata:
  name: packages-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: packages
  template:
    metadata: 
      labels: 
        app: packages
    spec:
      containers: 
        - name: packages
          image: jonathanmgomes/projeto-packages
          resources:
            limits:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata: 
  name: packages-clusterip-service
spec:
  # porta externa, acessível fora do cluster
  type: ClusterIP
  selector:
    app: packages
  ports:
    - name: packages
      protocol: TCP
      port: 3000
      targetPort: 3000
---
---
apiVersion: v1
kind: Service
metadata: 
  name: packages-service
spec:
  # porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: packages
  ports:
    - name: packages
      protocol: TCP
      port: 3000
      targetPort: 3000