apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: user
  template:
    metadata: 
      labels: 
        app: user
    spec:
      containers: 
        - name: user
          image: jonathanmgomes/projeto-user
          resources:
            limits:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata: 
  name: user-clusterip-service
spec:
  # porta externa, acessível fora do cluster
  type: ClusterIP
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: user-service
spec:
  # porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 5000
      targetPort: 5000
      expose: 