apiVersion: v1
kind: Service
metadata: 
  name: user-service
spec:
  # porta externa, acessível fora do cluster
  type: NodePort
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 5000
      targetPort: 5000