apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec: 
  replicas: 1 # Quantas cópias
  selector: 
    matchLabels:
      app: user
  template:
    metadata: 
      labels: 
        app: user
    spec:
      containers: 
        - name: user
          image: jonathanmgomes/projeto-user
           resources:
             limits:
               memory: 256Mi
               cpu: 1